### ISSUE TITLE
☸️ Add support for runtime config preset in the environment property

### ISSUE THREAD

**Issue by teroyks** [valohai/valohai-yaml#145]
Allow defining a `runtime_config` preset with the environment.
Both preset ID and slug should be supported.

Example (under `step` configuration):

```yaml
# with UUID
environment: g2.superduperlarge/f1bd21c8-ae31-451f-b75d-51cd0882aa1f

# with slug
environment: g2.superduperlarge/gpu-devices

# QOL: allow spaces for readability
environment: g2.superduperlarge / gpu-devices
```
