### ISSUE TITLE
String parameter with multiple values interpolates weirdly

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/valohai-yaml#39]
For this parameter:
```
    - name: models
      default:
      - DT
      - MLP-adam
      - MLP-sgd
      - RF
      - SVM
      - ada
      - kNN
      - lasso
      - linear
      multiple: separate
      multiple-separator: ' '
      optional: false
      pass-as: -c={v}
      type: string
```

The interpolation ends up with:
```
'-c=DT MLP-adam MLP-sgd RF SVM ada kNN lasso linear'
```

The expected interpolation is:
```
-c=DT MLP-adam MLP-sgd RF SVM ada kNN lasso linear
```
