### ISSUE TITLE
Allow steps to define icon and category

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/valohai-yaml#86]
For the step library project, we want show logos and bling-bling, if the steps are things like 3rd party data platforms.

Example:
```
 - step:
     name: snowflake-query
     image: valohai/dbconnectors
     command: python query.py {parameters}
     icon: https://valohai.com/img/orig/SNOW-35164165.png
     category: Database query
```
