### ISSUE TITLE
Support for parameter UI widgets (YAML)

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/valohai-yaml#88]
Support in YAML to ask for a custom UI widget for parameter editing like SQL or DatumAlias.

Example UI:
![Image](https://user-images.githubusercontent.com/1525350/215443518-b12bb253-977e-4fca-a87f-ba6785135408.png)

Example YAML:
```
 - step:
     name: snowflake-query
     image: valohai/dbconnectors
     command: python query.py {parameters}
     icon: https://valohai.com/img/orig/SNOW-35164165.png
     category: Database query
     parameters:
     - name: SQLquery
       type: string
       default: SELECT * FROM table
       widget: sql
     - name: datum_alias
       type: string
       widget: datumalias
```
