### ISSUE TITLE
Combobox widget for string parameters (YAML)

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/valohai-yaml#91]
For a string parameter, we want to offer predefined options + ability to edit the string. A.k.a combobox.

Currently you get enum dropdown using the `choices` in YAML:

```
 - step:
     name: mystep
     image: python:3.9
     command: python query.py {parameters}
     parameters:
     - name: huggingface-model
       type: string
       choices:
       - bert-base-cased
       - bert-base-uncased
```

We also need to give ability to type in a custom string.

```
 - step:
     name: mystep
     image: python:3.9
     command: python query.py {parameters}
     parameters:
     - name: huggingface-model
       type: string
       choices:
       - bert-base-cased
       - bert-base-uncased
       widget: 
         type: combobox
```
